CREATE TABLE QUERY (ID SERIAL PRIMARY KEY, q VARCHAR(255) NOT NULL, loc VARCHAR(255) NOT NULL);

CREATE TABLE EVENTS (
  ID SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  other1 VARCHAR(255) NOT NULL,
  other2 VARCHAR(255) NOT NULL,
  query_id int,
  
  PRIMARY KEY (id),
  CONSTRAINT FK_USER FOREIGN KEY (query_id) REFERENCES QUERY(id) ON DELETE CASCADE
);

INSERT INTO QUERY (q, loc) VALUES  ('Coffee', 'Boston');

DROP TABLE QUERY;