CREATE TABLE QUERY (ID SERIAL PRIMARY KEY, q VARCHAR(255) NOT NULL, loc VARCHAR(255) NOT NULL);

CREATE TABLE EVENTS (
  ID SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  date_start DATE NOT NULL,
  date_when VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  venue_name VARCHAR(255) NOT NULL,
  venue_rating VARCHAR(255) NOT NULL,
  venue_reviews VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(255) NOT NULL,
  query_id int,
  
  CONSTRAINT FK_QUERY FOREIGN KEY (query_id) REFERENCES QUERY(id) ON DELETE CASCADE
);

CREATE TABLE COVID_DATA (
  ID SERIAL PRIMARY KEY,
  address_line_one VARCHAR(255) NOT NULL,
  address_line_two VARCHAR(255) NOT NULL,
  zip VARCHAR(10) NOT NULL,
  zip4 VARCHAR(10) NOT NULL,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  covid_cases int NOT NULL,
  event_id int,

  CONSTRAINT FK_EVENT FOREIGN KEY (event_id) REFERENCES EVENTS(id) ON DELETE CASCADE
);

INSERT INTO QUERY (q, loc) VALUES  ('Coffee', 'Boston');

DROP TABLE QUERY;
