CREATE TABLE QUERY (ID SERIAL PRIMARY KEY, q VARCHAR(255) NOT NULL, loc VARCHAR(255) NOT NULL);

CREATE TABLE EVENTS (
  ID SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  date_start VARCHAR(255) NOT NULL,
  date_when VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  venue_name VARCHAR(255) NOT NULL,
  venue_rating VARCHAR(255) NOT NULL,
  venue_reviews VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(255) NOT NULL,
  query_id int,
  
  CONSTRAINT FK_QUERY FOREIGN KEY (query_id) REFERENCES QUERY(id) ON DELETE CASCADE
);

INSERT INTO QUERY (q, loc) VALUES  ('Coffee', 'Boston');

DROP TABLE QUERY;
